In [1]:
import numpy as np

In [11]:
b=np.array([(90,22,30,75,69),(66,28,2,3,99),(34,65,43,9,81),
           (18,82,61,70,20),(93,8,77,81,72)])
b

array([[90, 22, 30, 75, 69],
       [66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81],
       [18, 82, 61, 70, 20],
       [93,  8, 77, 81, 72]])

In [4]:
#concatenate
mat1=np.random.randint(0,100,(2,4))
mat2=np.random.randint(0,100,(4,4))
                    
                       

In [12]:
mat1


array([[95, 25, 85,  3],
       [49, 25, 40, 53]])

In [13]:
mat2


array([[ 0, 86, 78, 82],
       [10, 20, 36, 42],
       [10, 36,  1, 30],
       [77, 45, 31, 40]])

In [14]:
np.concatenate((mat1,mat2))

array([[95, 25, 85,  3],
       [49, 25, 40, 53],
       [ 0, 86, 78, 82],
       [10, 20, 36, 42],
       [10, 36,  1, 30],
       [77, 45, 31, 40]])

In [3]:
import numpy as np
c=np.random.randint(0,50,(4,4))
c

array([[40, 19, 33,  0],
       [47, 26,  1,  3],
       [14, 34, 24,  4],
       [33, 19, 22, 28]])

In [4]:
d=np.random.randint(0,60,(4,4))
d

array([[20, 15, 31,  0],
       [13, 47, 49,  9],
       [15,  3, 37, 38],
       [11, 58,  2, 17]])

In [5]:
np.concatenate((c,d),axis=1)

array([[40, 19, 33,  0, 20, 15, 31,  0],
       [47, 26,  1,  3, 13, 47, 49,  9],
       [14, 34, 24,  4, 15,  3, 37, 38],
       [33, 19, 22, 28, 11, 58,  2, 17]])

In [7]:
t=np.array([(1,2,3),(4,5,6)])
s=np.append(t,[7,8,9])

In [8]:
t

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
s1=np.append(t,[[7,8,9]],axis=0)

In [11]:
s1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
s2=np.append(t,[[9,8,9],[7,1,2]],axis=1)

In [15]:
s2

array([[1, 2, 3, 9, 8, 9],
       [4, 5, 6, 7, 1, 2]])

In [26]:
#insert
a=np.array([[1,2],[3,4]])
# d=np.insert(a,1,(11))
d=np.insert(a,1,[11])


In [27]:
d

array([ 1, 11,  2,  3,  4])

In [29]:
a=np.insert(s1,1,[11,12,13],axis=1)

In [30]:
a

array([[ 1, 11,  2,  3],
       [ 4, 12,  5,  6],
       [ 7, 13,  8,  9]])

In [31]:
#split
a=np.arange(16).reshape(4,4)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
np.split(a,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [36]:
np.split(a,2,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [37]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [38]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [39]:
#stack
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.stack((a,b))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [41]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
a=np.arange(12).reshape(3,4)

In [43]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.delete(a,6)

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11])