In [1]:
import numpy as np
b=np.array([(1,2,3,4),(5,6,7,800)])
b


array([[  1,   2,   3,   4],
       [  5,   6,   7, 800]])

In [2]:
b.shape

(2, 4)

In [3]:
b.size

8

In [4]:
b.ndim

2

In [5]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [14]:
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [24]:
np.eye(4).astype(int) #typecating

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [25]:
np.random.rand(4)

array([0.20196914, 0.17820954, 0.51637968, 0.20419166])

In [26]:
np.random.rand(3,4)

array([[0.77326964, 0.47659053, 0.12583031, 0.77561439],
       [0.64248812, 0.35018192, 0.63153506, 0.64261225],
       [0.98953018, 0.2207898 , 0.26003497, 0.6558437 ]])

In [27]:
             np.random.rand(3,4)*100

array([[84.17768915, 16.20924093,  0.86370198, 71.68247604],
       [87.16482487, 15.7687787 , 67.72994732, 67.2772449 ],
       [86.92449746, 41.03954784, 61.33328524, 83.12877445]])

In [28]:
 np.random.randint(1,10,(3,3))

array([[8, 1, 2],
       [6, 5, 2],
       [3, 5, 9]])

In [33]:
#mathematical operators
b=np.array([(1,2,3,4)])
a=np.array([(1,2,3,4)] )   
np.add(b,a)

array([[2, 4, 6, 8]])

In [34]:
np.subtract(b,a)

array([[0, 0, 0, 0]])

In [35]:
np.multiply(b,a)

array([[ 1,  4,  9, 16]])

In [37]:
np.divide(b,a).astype(int)

array([[1, 1, 1, 1]])

In [38]:
c=np.array([(1,2,3),(4,5,6),(7,8,9)])
d=np.array([(1,4,5),(9,6,8),(1,2,3)])

In [39]:
np.add(c,d)

array([[ 2,  6,  8],
       [13, 11, 14],
       [ 8, 10, 12]])

In [40]:
np.subtract(c,d)

array([[ 0, -2, -2],
       [-5, -1, -2],
       [ 6,  6,  6]])

In [41]:
np.multiply(c,d)

array([[ 1,  8, 15],
       [36, 30, 48],
       [ 7, 16, 27]])

In [42]:
np.divide(c,d).astype(int)

array([[1, 0, 0],
       [0, 0, 0],
       [7, 4, 3]])

In [46]:
a=np.array([-2,-3,-4,6])
np.abs(a)

array([2, 3, 4, 6])

In [47]:
c=np.array([(1,2,3),(4,5,6),(7,8,9)])
d=np.array([(1,4,5),(9,6,8),(1,2,3)])
np.mod(c,d)

array([[0, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [48]:
b=np.array([(1,2,3,4)])
a=np.array([(1,2,3,4)] )   
np.mod(b,a)

array([[0, 0, 0, 0]])

In [49]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ]])

In [50]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362]])

In [51]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128]])

In [52]:
np.exp(a)

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

In [54]:
np.power(a,2)

array([[ 1,  4,  9, 16]], dtype=int32)

In [56]:
    #statistical operator
a=np.array([5,6,7,8,90])
np.max(a)

90

In [57]:
np.mean(a)

23.2

In [58]:
np.median(a)

7.0

In [59]:
np.std(a)

33.41496670655232

In [61]:
c=np.array([(1,2,3),(5,6,7),(8,9,10)])
np.mean(c)

5.666666666666667

In [62]:
#return mean columnwise
np.mean(c,axis=0)

array([4.66666667, 5.66666667, 6.66666667])

In [63]:
np.mean(c,axis=1)

array([2., 6., 9.])

In [64]:
#rowwisemaximum
np.max(c,axis=1)

array([ 3,  7, 10])

In [65]:
np.min(c,axis=1)

array([1, 5, 8])

In [66]:
np.divide(c,2)

array([[0.5, 1. , 1.5],
       [2.5, 3. , 3.5],
       [4. , 4.5, 5. ]])

In [67]:
np.multiply(c,3)

array([[ 3,  6,  9],
       [15, 18, 21],
       [24, 27, 30]])

In [71]:
a=np.array([9,1,2,3]).reshape(2,2)
b=np.array([3,2,1,0]).reshape(2,2)
np.dot(a,b)

array([[28, 18],
       [ 9,  4]])

In [72]:
np.transpose(a)

array([[9, 2],
       [1, 3]])

In [74]:
a.T

array([[9, 2],
       [1, 3]])

In [78]:
d=np.array([(1,2,3),(5,6,7),(8,9,10)])
np.linalg.inv(a)

array([[ 0.12, -0.04],
       [-0.08,  0.36]])

In [79]:
d=np.array([(1,2,3),(5,6,7),(8,9,10)])
np.linalg.det(d)*

0.0

In [80]:
d=np.array([(1,2,3),(5,6,7),(8,9,10)])
np.unique(d)

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [82]:
e=np.array([ 1,  2,  3,  8,  6,  7,  8,  9, 10])
np.unique(e)

array([ 1,  2,  3,  6,  7,  8,  9, 10])

In [85]:
#repeat
e=np.array([ 1,  2,  3,  8,  6,  7,  8,  9, 10])
np.repeat(e,3)

array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  8,  8,  8,  6,  6,  6,  7,  7,
        7,  8,  8,  8,  9,  9,  9, 10, 10, 10])

In [88]:
#where
np.where(e==3)

(array([2], dtype=int64),)

In [89]:
#indexing
e[3]

8

In [91]:
slice=np.array([(1,2,3),
                (4,5,6),
                (7,8,9)])
slice[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [92]:
slice[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [93]:
slice[2:4,0:2]

array([[7, 8]])

In [94]:
#1d array slicing
a=np.array([55,6,7,9])
a[0:3]

array([55,  6,  7])

In [95]:
b=np.array([(90,22,30,75,69),(66,28,2,3,99),(34,65,43,9,81),
           (18,82,61,70,20),(93,8,77,81,72)])
b

array([[90, 22, 30, 75, 69],
       [66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81],
       [18, 82, 61, 70, 20],
       [93,  8, 77, 81, 72]])

In [98]:
b[1:4:2,1:4:2]

array([[28,  3],
       [82, 70]])

In [99]:
b[:,2:4]

array([[30, 75],
       [ 2,  3],
       [43,  9],
       [61, 70],
       [77, 81]])

In [100]:
b[:,:]

array([[90, 22, 30, 75, 69],
       [66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81],
       [18, 82, 61, 70, 20],
       [93,  8, 77, 81, 72]])