In [1]:
import numpy as np

<h1>creating array from list</h1>

In [2]:
a1d=np.array([1,2,3,45,6])
print(a1d)

[ 1  2  3 45  6]


In [3]:
a2d=np.array([[1,2,3,45,6],[1,2,3,45,6]])
print(a2d)

[[ 1  2  3 45  6]
 [ 1  2  3 45  6]]


In [5]:
np_array=np.array([1,2,3])
print(np_array*2)#element wise multiplication

[2 4 6]


In [9]:

import time
start=time.time()
np_array=np.arange(1000000)*2
print(time.time() - start)

0.01598191261291504


<h1>creating array from sratch</h1>

In [10]:
zeros=np.zeros((3,4))
print("zeros array:\n",zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones=np.ones((3,4))
print("ones array:\n",ones)

ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:

#special array with full method
full=np.full((3,4),36)
print("full array:\n",full)

full array:
 [[36 36 36 36]
 [36 36 36 36]
 [36 36 36 36]]


In [13]:
#random
random=np.random.random((3,4))
print("random array:\n",random)


random array:
 [[0.67131674 0.76296889 0.28866511 0.15985396]
 [0.20343079 0.44320299 0.09403467 0.14110336]
 [0.14961323 0.50354146 0.4041212  0.67752724]]


In [16]:
#range
sequence=np.arange(0,10,2)
print("sequence array:\n",sequence)

sequence array:
 [0 2 4 6 8]


In [17]:
sequence=np.arange(0,11,2)
print("sequence array:\n",sequence)

sequence array:
 [ 0  2  4  6  8 10]


<h1>Vector,matrix,tensor</h1>

In [18]:
vector=np.array([1,2,3])
print("vector:",vector)


vector: [1 2 3]


In [20]:
matrix=np.array([[1,2,3],
                [4,5,6]])
print("matrix:",matrix)


matrix: [[1 2 3]
 [4 5 6]]


In [26]:
tensor=np.array([[[1,2],[3,9]],
                 [[4,5],[8,6]]])
print("tensor:",tensor)


tensor: [[[1 2]
  [3 9]]

 [[4 5]
  [8 6]]]


<h1>array properties
</h1>

In [27]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)

shape (2, 3)
dimension 2
size 6
Dtype int32


In [29]:
arr=np.array([[1,2,True],
              [4,5,6]])
print("shape",arr.shape)
print("dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)

shape (2, 3)
dimension 2
size 6
Dtype int32


<h1>array reshaping</h1>


In [34]:
arr=np.arange(12)
print("orginal array",arr)
#reshapedarray
reshapedarray=arr.reshape((3,4))
print("\nreshapedarray",reshapedarray)


orginal array [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshapedarray [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
#flatten(returns copy of orginal array)
flatten=reshapedarray.flatten()
print("flatten",flatten)

flatten [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
#ravel(returns orginal array)
ravel=reshapedarray.ravel()
print("ravel",ravel)

ravel [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [40]:
#transpose
transpose=reshapedarray.T
print("\n Transpose array",transpose)


 Transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


<h1>Numpy array operations</h1>

In [42]:
arr=np.array([ 0 , 1 , 2 , 3 , 4  ,5 , 6 ,7 , 8 , 9, 10, 11])
print("basic slicing",arr[2:7])

basic slicing [2 3 4 5 6]


In [43]:
print("with step",arr[1:8:2])

with step [1 3 5 7]


In [44]:
print("Negative indexing",arr[-3])

Negative indexing 9


In [6]:
import numpy as np
arr2d=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print("Specific element",arr2d[1,2])
print("entire row",arr2d[1])
print("entire column:",arr2d[:,1])

Specific element 7
entire row [5 6 7 8]
entire column: [ 2  6 10]


<h1>Sorting</h1>

In [7]:
unsorted=np.array([3,1,4,55,76,245,4,6])
print("sorted array",np.sort(unsorted))

sorted array [  1   3   4   4   6  55  76 245]


In [13]:
arr2d_unsorted=np.array([[3,1],[4,55],[76,245],[4,6]])
print("sorted array",np.sort(arr2d_unsorted,axis=1))

sorted array [[  1   3]
 [  4  55]
 [ 76 245]
 [  4   6]]
