In [1]:
import numpy as np
#to create a 1-D array 
a = np.array([1,2,3,4,5]) 
a


array([1, 2, 3, 4, 5])

In [2]:
type(a)  #ndarry : n-dimensional array


numpy.ndarray

In [3]:
#tuple to array 
a = np.array((1,2,3,4,5)) 
a


array([1, 2, 3, 4, 5])

In [4]:
#set to array 
s = np.array({3,3,3,3,6,5,4,5,6,4,4}) 
s

array({3, 4, 5, 6}, dtype=object)

In [5]:
# dictionary to array 
d = np.array({'a':1,'b':2,'c':3}) 
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [3]:
#2-D array 
import numpy as np
a = np.array([(2,3,4),(5,6,7),(8,9,10)])
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
a = np.array([(1,2,3),(4,5,6)]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
b=np.array([(9,8,2,7),(1,2,8,9),(6,5,4,2)])
b

array([[9, 8, 2, 7],
       [1, 2, 8, 9],
       [6, 5, 4, 2]])

In [43]:
b = np.array([(1,2,3,4),(5,6,7,8),(9,3,6,8)])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 3, 6, 8]])

In [105]:
#array attributes 
b.shape  #to check the shape of an array

(3, 4)

In [10]:
b.size  #to check number of elements


12

In [11]:
b.ndim #to check number of dimensions


2

In [5]:
#arange : returns a 1-D array of given range 
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
#zeros 
np.zeros(4)

array([0., 0., 0., 0.])

In [107]:
a = np.zeros((4,4),dtype=int) 
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
#ones 
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#full 
np.full((4,5),8)


array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [49]:
np.linspace(1,100,4)


array([  1.,  34.,  67., 100.])

In [51]:
#identity array
np.eye(3).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [111]:
#random float values
np.random.rand(4)

array([0.48407942, 0.4712223 , 0.87145409, 0.03852288])

In [113]:
np.random.rand(3,4)

array([[0.33151742, 0.21777656, 0.41100143, 0.22188374],
       [0.98225215, 0.68667185, 0.83013171, 0.96081379],
       [0.98657708, 0.29558819, 0.25394971, 0.82102534]])

In [114]:
np.random.rand(3,4)*100

array([[19.48266352, 71.73658295, 80.71125978, 66.16753758],
       [ 3.53958929, 22.83994384, 59.06192786, 82.96862418],
       [ 1.74492636, 20.14771295, 42.229005  , 20.05957092]])

In [117]:
np.random.randint(1,10,(3,3))

array([[6, 2, 6],
       [8, 4, 1],
       [4, 5, 6]])

In [11]:
# Mathematical operations
a=np.array([4,5,6,7])
b=np.array([5,7,2,3])


In [5]:
np.add(a,b)

array([ 9, 12,  8, 10])

In [13]:
np.subtract(a,b)

array([-1, -2,  4,  4])

In [15]:
np.multiply(a,b)

array([20, 35, 12, 21])

In [17]:
np.divide(a,b)

array([0.8       , 0.71428571, 3.        , 2.33333333])

In [19]:
c=np.array([(1,2,3),(4,5,6),(7,8,9)])
d=np.array([(3,4,2),(6,2,5),(1,6,8)])

In [21]:
np.add(c,d)

array([[ 4,  6,  5],
       [10,  7, 11],
       [ 8, 14, 17]])

In [9]:
np.subtract(c,d)

array([[-2, -2,  1],
       [-2,  3,  1],
       [ 6,  2,  1]])

In [10]:
np.multiply(c,d)

array([[ 3,  8,  6],
       [24, 10, 30],
       [ 7, 48, 72]])

In [11]:
np.divide(c,d)

array([[0.33333333, 0.5       , 1.5       ],
       [0.66666667, 2.5       , 1.2       ],
       [7.        , 1.33333333, 1.125     ]])

In [13]:
a=np.array([-2,-3,1,5])
np.abs(a)

array([2, 3, 1, 5])

In [14]:
a1=np.array([4,8,10,12])
a2=np.array([3,2,5,6])
np.mod(a1,a2)

array([1, 0, 0, 0])

In [15]:
np.sin(a)

array([-0.90929743, -0.14112001,  0.84147098, -0.95892427])

In [17]:
np.log(a1)

array([1.38629436, 2.07944154, 2.30258509, 2.48490665])

In [18]:
np.tan(a1)

array([ 1.15782128, -6.79971146,  0.64836083, -0.63585993])

In [19]:
np.cos(a1)

array([-0.65364362, -0.14550003, -0.83907153,  0.84385396])

In [20]:
np.exp(a1)

array([5.45981500e+01, 2.98095799e+03, 2.20264658e+04, 1.62754791e+05])

In [21]:
np.power(a1,2)

array([ 16,  64, 100, 144], dtype=int32)

In [22]:
# statistical opeartions
a=np.array([5,6,8,9,20])
np.max(a)

20

In [23]:
np.min(a)

5

In [24]:
np.mean(a)

9.6

In [25]:
np.median(a)

8.0

In [26]:
np.std(a)

5.388877434122992

In [27]:
np.var(a)

29.04

In [23]:
c=np.array([(2,3,4),(5,6,7),(8,9,10)])
np.mean(c)


6.0

In [25]:
#returns mean row-wise
np.mean(c,axis=1)

array([3., 6., 9.])

In [30]:
#returns mean column wise
np.mean(c,axis=0)

array([5., 6., 7.])

In [31]:
#returns max value row wise
np.max(c,axis=1)

array([ 4,  7, 10])

In [32]:
#returns minimum value row wise
np.min(c,axis=1)

array([2, 5, 8])

In [33]:
#Scalar math
a=np.array([4,3,6,7])
np.add(a,2)

array([6, 5, 8, 9])

In [34]:
np.subtract(a,2)

array([2, 1, 4, 5])

In [35]:
np.multiply(a,3)

array([12,  9, 18, 21])

In [36]:
np.divide(a,2)

array([2. , 1.5, 3. , 3.5])

In [27]:
#dot product
a=np.array([0,1,2,3]).reshape(2,2)
b=np.array([3,2,0,1]).reshape(2,2)
np.dot(a,b)

array([[0, 1],
       [6, 7]])

In [29]:
a

array([[0, 1],
       [2, 3]])

In [31]:
b

array([[3, 2],
       [0, 1]])

In [33]:
np.transpose(a)

array([[0, 2],
       [1, 3]])

In [41]:
a=np.array([(2,3,4),(5,6,7),(1,2,8)])
np.linalg.inv(a)


array([[-2.26666667,  1.06666667,  0.2       ],
       [ 2.2       , -0.8       , -0.4       ],
       [-0.26666667,  0.06666667,  0.2       ]])

In [42]:
np.linalg.det(a)

-14.999999999999993

In [43]:
d=np.array([0,1,1,1,3,3,5,5,5])
np.unique(d)

array([0, 1, 3, 5])

In [35]:
#repeat
a=np.array([1,2,3,4])
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [53]:
# where
a=np.array([1,2,3,4,5])
np.where(a==2)

(array([1], dtype=int64),)

In [46]:
#indexing
a=np.array([1,2,3,4])
a[0]

1

In [55]:
b=np.array([(2,3,4),(8,4,5),(6,2,4)])

In [57]:
#indexing
b[2,2]

4

In [ ]:


#1-d array slicing
a=np.array([5,6,7,8,9])
a[0:3]

In [ ]:
#mat[row_slice,column_slice]
#row_slice = start_row : end_row + 1 : step
#column_slice = start_col : end_col + 1 : step
a=np.array([(4,5,7,8),(2,3,9,2),(6,4,1,0)])
a[1:3,1:3]
           



In [39]:
b=np.array([(90,22,30,75,69),(66,28,2,3,99),(34,65,43,9,81),
            (18,82,61,70,20),(93,8,77,81,72)])
b

array([[90, 22, 30, 75, 69],
       [66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81],
       [18, 82, 61, 70, 20],
       [93,  8, 77, 81, 72]])

In [41]:
b[2:4,1:4:2]

array([[65,  9],
       [82, 70]])

In [57]:
b[:,2:4]

array([[30, 75],
       [ 2,  3],
       [43,  9],
       [61, 70],
       [77, 81]])

In [58]:
b[1:3,:]

array([[66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81]])

In [59]:
b[:,:]

array([[90, 22, 30, 75, 69],
       [66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81],
       [18, 82, 61, 70, 20],
       [93,  8, 77, 81, 72]])

In [60]:
#array manipulation
#concatenate
mat1 = np.random.randint(0,100,(2,4))
mat2 = np.random.randint(0,100,(4,4))

In [61]:
mat1

array([[40, 80, 28, 48],
       [77, 30, 24,  6]])

In [62]:
mat2

array([[ 0, 11, 57, 27],
       [ 8, 66, 41, 22],
       [74, 90, 32, 29],
       [14, 99, 84, 84]])

In [66]:
np.concatenate((mat1,mat2))

array([[40, 80, 28, 48],
       [77, 30, 24,  6],
       [ 0, 11, 57, 27],
       [ 8, 66, 41, 22],
       [74, 90, 32, 29],
       [14, 99, 84, 84]])

In [3]:
import numpy as np
c=np.random.randint(0,50,(4,4))
c

array([[ 7, 49, 29, 46],
       [37,  8, 24, 36],
       [ 1, 24, 13, 20],
       [22,  8, 20, 43]])

In [5]:
d=np.random.randint(10,60,(4,4))
d

array([[43, 17, 24, 24],
       [29, 36, 47, 22],
       [56, 58, 43, 55],
       [53, 17, 37, 11]])

In [7]:
np.concatenate((c,d),axis=1)

array([[ 7, 49, 29, 46, 43, 17, 24, 24],
       [37,  8, 24, 36, 29, 36, 47, 22],
       [ 1, 24, 13, 20, 56, 58, 43, 55],
       [22,  8, 20, 43, 53, 17, 37, 11]])

In [9]:
#append: add value at end of array,numpy.append(arr, values, axis)
t=np.array([(1,2,3),(4,5,6)]) 
s=np.append(t,[7,8,9])

In [11]:
t

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
s.shape

(9,)

In [75]:
s1=np.append(t, [[7,8,9]],axis = 0)

In [76]:
s1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
t

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
s2=np.append(t,[[5,6,8],[7,1,2]], axis=1)

In [80]:
s2

array([[1, 2, 3, 5, 6, 8],
       [4, 5, 6, 7, 1, 2]])

In [49]:
#insert: This function inserts values in the input array along 
#the given axis and before the given index.
#numpy.insert(arr, obj, values, axis)
a = np.array([[1,2],[3,4],[5,6]]) 
d=np.insert(a,1,[11])

In [51]:
d

array([ 1, 11,  2,  3,  4,  5,  6])

In [53]:
b=np.insert(a,1,[11],axis = 0) 

In [55]:
b

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [57]:
b=np.insert(a,1,[11,12,13],axis = 1) 

In [59]:
b

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [33]:
#split
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
np.split(a,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [89]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [90]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [91]:
np.split(a,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [92]:
c=np.arange(1,11)

In [93]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
c.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [61]:
#stack:This function joins the sequence of arrays along a new axis
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) 
np.stack((a,b))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [96]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [97]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [99]:
#This function returns a new array with the specified subarray deleted from the input array
#Numpy.delete(arr, obj, axis)
a = np.arange(12).reshape(3,4) 


In [100]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a2=np.delete(a,5)

In [102]:
a2

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])