In [4]:
#break 
for i in 'python':
    if i=='h':
        break
    print(i)



p
y
t


In [5]:
#continue
for i in 'python':
    if i=='h':
        continue
    print(i)


p
y
t
o
n


In [6]:
#  pass
for i in 'python':
    if i=='h':
        pass
    print(i)


p
y
t
h
o
n


<h1>Functions:a reusable piece of code. block of statements that does some specific task and returns something</h1>

In [7]:
print("hello")

hello


In [8]:
max(10,20,30)

30

In [9]:
min(1,3,-1,0)

-1

In [10]:
min(0-1,2)


-1

In [12]:
sum([20,30,40])

90

In [13]:
len("bigya")

5

In [14]:
#no argument
def greet():
    print('hello')

greet()

hello


In [15]:
#SIngle argument
def greet(name):
    print('hello',name)

greet("bigya")

hello bigya


In [19]:
#double argument
def greet(name,caste):
    print('hello',name,caste)
    return

greet("bigya","gen")

hello bigya gen


In [25]:
# greet("bigya","gen")+greet("bigya","gen")

In [22]:
#default argument
def add(n=5,m=10):
    return n+m

add()

15

In [24]:
add(10,25)

35

In [26]:
#multiple arguments
def fun(*args):
    return sum(args)

fun(20,20,40)

80

In [29]:
#evenorodd
def isEven(n):
    if n%2==0:
        return 'Even'
    else:
        return 'Not Even'

isEven(4)

'Even'

In [30]:
def add(n):
    s=0
    for i in range(1,n+1):
        s+=i
    return s

add(10)

55

In [42]:
class Apple:
    color='orange'
    taste='sour'

obj=Apple()


In [43]:
obj.color

'orange'

In [44]:
obj.taste

'sour'

In [45]:
obj1=Apple()

In [50]:
obj1.color='green'


In [54]:
obj1.taste="sweet"

In [55]:
obj1.color

'green'

In [56]:
obj1.taste

'sweet'

In [58]:
class Apple:
    color='red'
    taste='sweet'
    def fun(abc):
        return "my name is bigyajeet"
obj=Apple()

In [59]:
obj.fun()

'my name is bigyajeet'

In [62]:
class Apple:
    color="red"
    taste="sweet"
    amount=100
    def price(self,qty):
        return self.amount*qty

obj=Apple()
obj.price(4)

400

In [81]:
class Bird:
    name=input("enter the name of the bird")
    age=int(input("enter the age of the bird"))
    color=input("enter the color of the bird")
    weight=int(input("enter the weight of the bird"))
    def eat(self,foodeaten):
        print("name is:",self.name,"age is:",self.age,"color is:",self.color,"weight is:",self.weight)
        print(self.weight+foodeaten,"kg",)

obj=Bird()
obj.eat(17)
        

enter the name of the bird mithu
enter the age of the bird 13
enter the color of the bird green
enter the weight of the bird 55


name is: mithu age is: 13 color is: green weight is: 55
72 kg


<h1>numpy</h1>

In [82]:
import numpy as np
#to create a 1-D array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [83]:
type(a)

numpy.ndarray

In [86]:
import numpy as np
#to create a 1-D array
a=np.array((1,2,3,4,5))
a
type(a)

numpy.ndarray

In [87]:
import numpy as np
#to create a 1-D array
a=np.array({1,2,3,4,5})
a
type(a)

numpy.ndarray

In [88]:
#dictionary to array
d=np.array({'a':1,'b':2,'c':3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [89]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
a=np.array([(4,3,2,1),(2,1,5,6),(1,9,5,7),(5,6,7,9)])
a

array([[4, 3, 2, 1],
       [2, 1, 5, 6],
       [1, 9, 5, 7],
       [5, 6, 7, 9]])